### ISSUE TITLE
More liberal license?

### ISSUE THREAD

**Issue by julianhyde** [learnedsystems/CEB#1]
GPL 3.0 is a very restrictive license. Please consider using a more liberal license, such as Apache, MIT or BSD. it will make it easier to embed this project in other projects.

**Comment by parimarjan** [comment]
Thank you for suggesting this! We would love for other projects to extend and reuse this work, and MIT license seems more appropriate for it indeed. We have updated the project license.

**Comment by julianhyde** [comment]
Thank you for changing the license!

By the way, for what it's worth, I learned about this project from a VLDB 21 talk. Good luck with this project.
